apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
specs:
  containers:
  - name: myapp
    image: nginx
  tolerations:
   - key: "spray"
  operator: "Equal"
  value: "mortien"
  effect: "NoSchedule"


  # Taints work on node level 
  # Toleration work on pod level 
  # Tainting node command : kubectl taint nodes node1 key1=value1:NoSchedule
  # Removing taint from node : kubectl taint nodes node1 key1=value1:NoSchedule- (putting hypen (-) at last is mandate)