apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
specs:
  containers:
  - name: myapp
    image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values:
            - ssd 