apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
      - name: my-storage
        mountPath: /home/ubuntu/rohit
  volumes: 
    - name: my-storage
      persistentVolumeCliam: 
      claimName: my-demo-claim