apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Reclaim
  storageClassName: local-storage
  local:
    path: /home/ubuntu/rohit
  nodeAffinity:
    recquired:
      nodeSelectorTerms:
      - matchExpressions:
        - key : kubernetes.io/hostname
          operator: In
          values:
          - node1