apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-demo-claim
spec:
  volumeName: demo-pv
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi